name: Check for Version Updates

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check-for-version-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Get Current and Main Branch Versions
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          git fetch origin main
          MAIN_VERSION=$(git show origin/main:package.json | node -p "JSON.parse(require('fs').readFileSync(0, 'utf-8')).version")
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "MAIN_VERSION=$MAIN_VERSION" >> $GITHUB_ENV

      - name: Compare Versions
        run: |
          if ! npx semver $CURRENT_VERSION -gt $MAIN_VERSION; then
            echo "🚨 Please update the version. Current version ($CURRENT_VERSION) should be greater than main version ($MAIN_VERSION)."
            exit 1
          fi
