name: Version Update

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ['Build and Test']
    types:
      - completed

jobs:
  version-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Get update type
        run: |
          cat $GITHUB_EVENT_PATH
